/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Mokleters
 */
public class Frame1 extends javax.swing.JFrame 
{
    String temp = "";
    Double tinggibdn, berat, hasil;

    public Frame1() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        tinggi = new javax.swing.JTextField();
        bb = new javax.swing.JTextField();
        perempuan = new javax.swing.JRadioButton();
        laki = new javax.swing.JRadioButton();
        hitung = new javax.swing.JButton();
        cb = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ideal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        hsl = new javax.swing.JTextField();
        saran = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nama");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 50, 40, 20);

        jLabel2.setText("Tinggi");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 80, 40, 20);

        jLabel3.setText("Berat Badan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 110, 60, 20);

        jLabel4.setText("Jenis Kelamin");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 150, 80, 20);

        jLabel5.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 20, 100, 30);
        getContentPane().add(nama);
        nama.setBounds(140, 50, 140, 20);
        getContentPane().add(tinggi);
        tinggi.setBounds(140, 80, 50, 20);
        getContentPane().add(bb);
        bb.setBounds(140, 110, 50, 20);

        perempuan.setText("Perempuan");
        getContentPane().add(perempuan);
        perempuan.setBounds(140, 150, 79, 23);

        laki.setText("Laki-Laki");
        getContentPane().add(laki);
        laki.setBounds(250, 150, 65, 23);

        hitung.setBackground(new java.awt.Color(255, 204, 204));
        hitung.setText("Hitung");
        hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitungActionPerformed(evt);
            }
        });
        getContentPane().add(hitung);
        hitung.setBounds(50, 190, 70, 23);

        cb.setBackground(new java.awt.Color(255, 204, 204));
        cb.setText("Coba Lagi");
        cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbActionPerformed(evt);
            }
        });
        getContentPane().add(cb);
        cb.setBounds(130, 190, 79, 20);

        keluar.setBackground(new java.awt.Color(255, 204, 204));
        keluar.setText("Keluar");
        keluar.setToolTipText("");
        keluar.setAutoscrolls(true);
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        getContentPane().add(keluar);
        keluar.setBounds(220, 190, 63, 23);

        jLabel6.setText("Berat badan ideal anda adalah :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 250, 160, 14);

        jLabel7.setText("cm");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 80, 34, 14);

        jLabel8.setText("Kg");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(300, 250, 34, 14);
        getContentPane().add(ideal);
        ideal.setBounds(240, 250, 60, 20);

        jLabel9.setText("Kg");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(190, 110, 34, 14);

        jLabel10.setForeground(new java.awt.Color(0, 51, 255));
        jLabel10.setText("Hasil Diagnosa Kesehatan ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(130, 290, 130, 14);
        getContentPane().add(hsl);
        hsl.setBounds(70, 310, 250, 20);
        getContentPane().add(saran);
        saran.setBounds(70, 340, 250, 20);

        setBounds(0, 0, 416, 443);
    }// </editor-fold>//GEN-END:initComponents

    private void hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitungActionPerformed
        // TODO add your handling code here:
        if (nama.getText().equals("")||bb.getText().equals("")||tinggi.getText().equals(""))
        {
            JOptionpane.showMessageDialog(null, "Kotak isian harus diisi");
        }else if (perempuan.isSelected()||laki.isSelected())
        {
            try {
                proses();
            }catch (Exception e){
                JOptionpane.showMessageDialog(null, "Masukan ada yang salah");
            }
        } else {
            JOptionpane.showMessageDialog(null, "Radio button harus dipilih");
        }
        
    }//GEN-LAST:event_hitungActionPerformed

    private void cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbActionPerformed
        // TODO add your handling code here:
        nama.setText("");
        tinggi.setText("");
        bb.setText("");
        perempuan.setSelected(false);
        laki.setSelected(false);
        ideal.setText("");
        hsl.setText("");
        saran.setText("");
    }//GEN-LAST:event_cbActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cb;
    private javax.swing.JButton hitung;
    private javax.swing.JTextField hsl;
    private javax.swing.JTextField ideal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton keluar;
    private javax.swing.JRadioButton laki;
    private javax.swing.JTextField nama;
    private javax.swing.JRadioButton perempuan;
    private javax.swing.JTextField saran;
    private javax.swing.JTextField tinggi;
    // End of variables declaration//GEN-END:variables

    private void proses() 
    {
        tinggibdn = Double.parseDouble(tinggi.getText());
        berat = Double.parseDouble(bb.getText());
        
        if (perempuan.isSelected())
        {
            hasil = (tinggibdn - 110) * 1;
        } else if (laki.isSelected())
        {
            hasil = (tinggibdn - 100) * 1;
        }
        temp = Double.toString(hasil.intValue());
        
        if (hasil<berat){
            ideal.setText(temp);
            hsl.setText("Maaf " + nama.getText() + " ,Sepertinya anda Overweight : ( ");
            saran.setText("Banyaklah berolahraga");
        }
        else if (hasil > berat)
        {
            ideal.setText(temp);
            hsl.setText("Maaf " + nama.getText() + " ,Sepertinya anda Underweight : ( ");
            saran.setText("Banyak makan makanan bergizi dan berkarbohidrat");
        }
        else
        {
            ideal.setText(temp);
            hsl.setText("Hallo " + nama.getText() + " ,Berat badan ideal : ( ");
            saran.setText("lanjutkan polamakan dan gaya hidup sehat");
        }
    }
}
